#define ORDER_BASE 0

#define YELLOW_GATE_WAITING 0//1번, 10번 장애물
#define YELLOW_GATE_READY_TO_GO 1
#define YELLOW_GATE_NEXT_OBSTACLE 2

#define RED_BRIDGE_BEFORE_THE_STAIRS 0//2번 장애물
#define RED_BRIDGE_NEXT_OBSTACLE 1

#define BLACKMINE_SELECT_BSETWAY 0//3번 장애물
#define BLACKMINE_MOVING 1
#define BLACKMINE_NEXT_OBSTACLE 2

#define BLUE_HURDLE_GOING 0//4번 장애물
#define BLUE_HURDLE_FIND_CENTER 1
#define BLUE_HURDLE_NEXT_OBSTACLE 2

#define BLUE_GATE_FINDING_GATE_DIRECTION 0//5번 장애물, 9번 장애물
#define BLUE_GATE_NEXT_OBSTACLE 1

#define GREEN_BRIDGE_FIND 0
#define GREEN_BRIDGE_ON_THE_BRIDGE 1
#define GREEN_BRIDGE_DOWN 2
#define GREEN_BRIDGE_NEXT_OBSTACLE 3

#define BLUE_HOLE_NOT_KICK 0
#define BLUE_HOLE_KICK 1

#define YELLOW_BRIDGE_BEFORE_THE_STAIRS 0//8번 장애물
#define YELLOW_BRIDGE_ON_THE_BRIDGE 1
#define YELLOW_BRIDGE_DOWN 2
#define YELLOW_BRIDGE_NEXT_OBSTACLE 3
